### ISSUE TITLE
_datasette_auth_tokens should work with multiple databases

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-auth-tokens#11]
Right now the plugin gets confused about which of multiple databases should have the `_datasette_auth_tokens` table created in it.

Plus this link `/-/api/tokens/1` can error if there are multiple databases and it looks in the wrong one, because: https://github.com/simonw/datasette-auth-tokens/blob/d84cb32678dfa540a9d06ca9744968cdeaa36283/datasette_auth_tokens/views.py#L169C14-L176

**Comment by simonw** [comment]
Solution:
```yaml
plugins:
  datasette-auth-tokens:
    manage_tokens: true
    manage_tokens_database: data
```
